name: Autocalificación Ejercicios IA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Instalar dependencias
      run: |
        pip install experta nbformat jupyter pytest
    
    - name: Convertir notebook y ejecutar tests
      run: |
        python tests/test_ejercicio1.py
    
    - name: Mostrar resultados
      if: always()
      run: |
        if [ -f test_results.txt ]; then
          cat test_results.txt
        fi
